// src/components/common/Label.tsx
import { FC, LabelHTMLAttributes } from 'react'

import { twsx } from '../../utils/dom'

export type LabelProps = LabelHTMLAttributes<HTMLLabelElement> & {
  error?: unknown
}

const Label: FC<LabelProps> = ({ children, error, className, ...props }) => (
  <label
    className={twsx(
      'block text-sm',
      error ? 'text-error-600' : 'text-gray-700',
      className
    )}
    {...props}
  >
    {children}
  </label>
)

export default Label

// src/lib/atoms/Label.svelte
<script lang="ts">
  import { tw } from '$lib/utils/dom'

  let for_: string | undefined = undefined
  export { for_ as for }

  let class_: string | undefined = undefined
  export { class_ as class }
</script>

<label class={tw('text-sm text-gray-600 transition dark:text-gray-400', class_)} for={for_}>
  <slot />
</label>
