// src/routes/genres/[id]/history/+page.svelte
<script lang="ts">
  import IconButton from '$lib/atoms/IconButton.svelte'
  import LinkButton from '$lib/atoms/LinkButton.svelte'
  import ChevronRightIcon from '$lib/icons/ChevronRightIcon.svelte'
  import { toPrettyDate } from '$lib/utils/datetime'
  import { cn } from '$lib/utils/dom'
  import { capitalize } from '$lib/utils/string'

  import Footer from '../../Footer.svelte'
  import GenrePageHeader from '../GenrePageHeader.svelte'
  import type { PageData } from './$types'
  import Diff from './Diff.svelte'

  export let data: PageData

  $: latestEntry = data.genreHistory.at(-1)

  let expanded = new Set()

  function setExpanded(id: number, value: boolean) {
    if (value) {
      expanded.add(id)
    } else {
      expanded.delete(id)
    }
    expanded = expanded
  }
</script>

<div class="flex h-full flex-col">
  {#if !latestEntry}
    <div>No history found :(</div>
  {:else}
    <GenrePageHeader id={data.id} name={latestEntry.name} subtitle={latestEntry.subtitle} />

    <div class="flex-1 overflow-auto p-2 py-4">
      {#if data.genreHistory.length > 0}
        <table class="w-full table-auto">
          <thead>
            <tr>
              <th />
              <th class="p-1 px-2 text-left">Change</th>
              <th class="p-1 px-2 text-left">Contributor</th>
              <th class="p-1 px-2 text-left">Date</th>
            </tr>
          </thead>
          <tbody>
            {#each data.genreHistory as entry, i (entry.id)}
              {@const isExpanded = expanded.has(entry.id)}
              {@const previousHistory = data.genreHistory[i - 1]}
              <tr>
                <td class="w-px p-1 px-2">
                  <IconButton
                    tooltip={isExpanded ? 'Collapse' : 'Expand'}
                    on:click={() => setExpanded(entry.id, !isExpanded)}
                  >
                    <ChevronRightIcon class={cn('transition', isExpanded && 'rotate-90')} />
                  </IconButton>
                </td>
                <td class="p-1 px-2">{capitalize(entry.operation)}</td>
                <td class="p-1 px-2">
                  {#if entry.account}
                    <a href="/accounts/{entry.account.id}" class="text-primary-500 hover:underline"
                      >{entry.account.username}</a
                    >
                  {:else}
                    <div class="text-gray-500 line-through">Deleted</div>
                  {/if}
                </td>
                <td class="p-1 px-2">{toPrettyDate(entry.createdAt)}</td>
              </tr>

              {#if isExpanded}
                <tr>
                  <td />
                  <td class="p-1 px-2" colSpan={3}>
                    <Diff {previousHistory} currentHistory={entry} genres={data.streamed.genres} />
                  </td>
                </tr>
              {/if}
            {/each}
          </tbody>
        </table>
      {:else}
        <div class="flex justify-center text-gray-600">No history</div>
      {/if}
    </div>
  {/if}

  <Footer>
    <LinkButton kind="outline" href="/genres/{data.id}">Back to genre page</LinkButton>
  </Footer>
</div>

// src/components/GenresPage/GenreView/History.tsx
import { CrudOperation } from '@prisma/client'
import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  useReactTable,
} from '@tanstack/react-table'
import { compareAsc, format } from 'date-fns'
import Link from 'next/link'
import { FC, useMemo } from 'react'
import { IoMdArrowBack } from 'react-icons/io'

import { DefaultGenreHistory } from '../../../server/db/genre-history/outputs'
import { useGenreHistoryQuery } from '../../../services/genre-history'
import { capitalize } from '../../../utils/string'
import GenreLink from '../../common/GenreLink'
import { CenteredLoader } from '../../common/Loader'

const GenreHistory: FC<{ id: number }> = ({ id }) => {
  const historyQuery = useGenreHistoryQuery(id)

  if (historyQuery.data) {
    return <HasData history={historyQuery.data} />
  }

  if (historyQuery.error) {
    return <div>Error fetching history :(</div>
  }

  return <CenteredLoader />
}

const columnHelper = createColumnHelper<DefaultGenreHistory>()

const defaultColumns = [
  columnHelper.accessor('operation', {
    header: 'Change',
    cell: (props) => capitalize(props.getValue()),
  }),
  columnHelper.accessor('account', {
    header: 'Contributor',
    cell: (props) => {
      const account = props.getValue()

      if (!account) {
        return <div className='text-gray-500 line-through'>Deleted</div>
      }

      return (
        <Link
          href={{
            pathname: '/accounts/[id]',
            query: { id: account.id.toString() },
          }}
        >
          <a className='text-primary-500 hover:underline'>{account.username}</a>
        </Link>
      )
    },
  }),
  columnHelper.accessor('createdAt', {
    header: 'Date',
    cell: (props) => format(props.getValue(), 'PPpp'),
  }),
]

const HasData: FC<{ history: DefaultGenreHistory[] }> = ({
  history: unsortedHistory,
}) => {
  const history = useMemo(
    () =>
      unsortedHistory.sort((a, b) => {
        // always show CREATE first
        if (
          a.operation === CrudOperation.CREATE &&
          b.operation !== CrudOperation.CREATE
        ) {
          return -1
        } else if (
          b.operation === CrudOperation.CREATE &&
          a.operation !== CrudOperation.CREATE
        ) {
          return 1
        }

        return compareAsc(a.createdAt, b.createdAt)
      }),
    [unsortedHistory]
  )

  const genre = useMemo(() => {
    const latestHistory = history[history.length - 1]
    if (!latestHistory) return
    return {
      id: latestHistory.treeGenreId,
      name: latestHistory.name,
      subtitle: latestHistory.subtitle,
    }
  }, [history])

  return (
    <div className='flex-1 overflow-auto p-4'>
      <div className='flex items-center border-b border-gray-100 pb-4'>
        {genre ? (
          <>
            <GenreLink
              id={genre.id}
              className='mr-1.5 rounded-full p-1.5 text-gray-600 hover:bg-primary-100 hover:text-primary-700'
            >
              <IoMdArrowBack size={18} />
            </GenreLink>
            <div className='text-2xl font-bold text-gray-600'>
              {genre.name}
              {genre.subtitle && (
                <>
                  {' '}
                  <span className='text-lg text-gray-500'>
                    [{genre.subtitle}]
                  </span>
                </>
              )}
            </div>
          </>
        ) : (
          <>
            <span className='mr-1.5 rounded-full p-1.5 text-gray-600 hover:bg-primary-100 hover:text-primary-700'>
              <IoMdArrowBack size={18} />
            </span>
            <div className='text-2xl font-bold text-gray-600'>Loading...</div>
          </>
        )}
      </div>

      <div className='pt-4'>
        {history.length > 0 ? (
          <Table history={history} />
        ) : (
          <div className='flex justify-center text-gray-600'>No history</div>
        )}
      </div>
    </div>
  )
}

const Table: FC<{ history: DefaultGenreHistory[] }> = ({ history }) => {
  const table = useReactTable({
    data: history,
    columns: defaultColumns,
    getCoreRowModel: getCoreRowModel(),
  })

  return (
    <table>
      <thead>
        {table.getHeaderGroups().map((headerGroup) => (
          <tr key={headerGroup.id}>
            {headerGroup.headers.map((header) => (
              <th key={header.id} className='p-1 px-2 text-left'>
                {header.isPlaceholder
                  ? null
                  : flexRender(
                      header.column.columnDef.header,
                      header.getContext()
                    )}
              </th>
            ))}
          </tr>
        ))}
      </thead>
      <tbody>
        {table.getRowModel().rows.map((row) => (
          <tr key={row.id}>
            {row.getVisibleCells().map((cell) => (
              <td key={cell.id} className='p-1 px-2'>
                {flexRender(cell.column.columnDef.cell, cell.getContext())}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
      <tfoot>
        {table.getFooterGroups().map((footerGroup) => (
          <tr key={footerGroup.id}>
            {footerGroup.headers.map((header) => (
              <th key={header.id}>
                {header.isPlaceholder
                  ? null
                  : flexRender(
                      header.column.columnDef.footer,
                      header.getContext()
                    )}
              </th>
            ))}
          </tr>
        ))}
      </tfoot>
    </table>
  )
}

export default GenreHistory
