// src/components/GenrePage/GenreTreeNode.tsx
import clsx from 'clsx'
import Link from 'next/link'
import { equals } from 'ramda'
import { FC, useEffect, useMemo, useState } from 'react'
import { RiArrowDownSLine, RiArrowRightSLine } from 'react-icons/ri'

import { isFullyVisible } from '../../utils/dom'
import { useGenrePageContext } from './context'
import GenreRelevanceChip from './GenreRelevanceChip'
import { useGenreTreeContext } from './GenreTreeContext'
import GenreTypeChip from './GenreTypeChip'
import { TreeNode } from './useGenreTreeQuery'
import useGenreTreeSettings from './useGenreTreeSettings'

const GenreTreeNode: FC<{ node: TreeNode }> = ({
  node: { key, path, genre, children },
}) => {
  const { id, childGenres, parentGenres, name, subtitle, relevance } = genre

  const { selectedPath, setSelectedPath, expanded, setExpanded } =
    useGenrePageContext()

  const isExpanded = useMemo(
    () => expanded[key] === 'expanded',
    [expanded, key]
  )

  const { showTypeTags, showRelevanceTags } = useGenreTreeSettings()

  const isSelected = useMemo(
    () => selectedPath && equals(selectedPath, path),
    [path, selectedPath]
  )

  const [ref, setRef] = useState<HTMLLIElement | null>(null)
  const { treeEl } = useGenreTreeContext()
  useEffect(() => {
    if (isSelected && ref && treeEl) {
      const visible = isFullyVisible(ref, treeEl)
      if (!visible) {
        ref.scrollIntoView()
      }
    }
  }, [isSelected, ref, treeEl])

  return (
    <li
      ref={setRef}
      className={clsx(parentGenres.length > 0 && 'ml-4 border-l')}
    >
      <div className='ml-1 flex space-x-1'>
        <button
          className={clsx(
            'p-1 hover:bg-blue-100 hover:text-blue-600 rounded-sm text-gray-500',
            childGenres.length === 0 && 'invisible'
          )}
          onClick={() =>
            setExpanded(key, isExpanded ? 'collapsed' : 'expanded')
          }
        >
          {isExpanded ? <RiArrowDownSLine /> : <RiArrowRightSLine />}
        </button>
        <Link
          href={{
            pathname: '/genres',
            query: { id: id.toString() },
          }}
        >
          <a
            onClick={() => setSelectedPath(path)}
            className={clsx(
              'hover:font-bold',
              isSelected ? 'text-blue-600 font-bold' : 'text-gray-600'
            )}
          >
            {name}
            {subtitle && (
              <>
                {' '}
                <span
                  className={clsx(
                    'text-sm',
                    isSelected ? 'text-blue-500' : 'text-gray-500'
                  )}
                >
                  [{subtitle}]
                </span>
              </>
            )}
            {showTypeTags && genre.type !== 'STYLE' && (
              <>
                {' '}
                <GenreTypeChip type={genre.type} />
              </>
            )}
            {showRelevanceTags && (
              <>
                {' '}
                <GenreRelevanceChip relevance={relevance} />
              </>
            )}
          </a>
        </Link>
      </div>
      {isExpanded && children.length > 0 && (
        <ul>
          {children.map((node) => (
            <GenreTreeNode key={node.key} node={node} />
          ))}
        </ul>
      )}
    </li>
  )
}

export default GenreTreeNode

// src/routes/genres/GenreNavigator/GenreTree/GenreTreeNode.svelte
<script lang="ts">
  import { equals } from 'ramda'

  import { browser } from '$app/environment'
  import IconButton from '$lib/atoms/IconButton.svelte'
  import GenreTypeChip from '$lib/components/GenreTypeChip.svelte'
  import { userSettings } from '$lib/contexts/user'
  import ChevronRightIcon from '$lib/icons/ChevronRightIcon.svelte'
  import { slide } from '$lib/transitions/slide'
  import { cn, isFullyVisible } from '$lib/utils/dom'

  import RelevanceChip from './RelevanceChip.svelte'
  import { treeState } from './state'

  export let id: number
  export let path: number[]
  export let treeRef: HTMLElement | undefined

  const genre = $treeState.genres.get(id)

  $: isSelected = $treeState.selectedPath && equals($treeState.selectedPath, path)
  $: isExpanded = $treeState.expanded.has(path.join('-'))

  let ref: HTMLElement | undefined
  $: if (isSelected && ref && treeRef && browser) {
    const visible = isFullyVisible(ref, treeRef)
    if (!visible) {
      ref.scrollIntoView()
    }
  }
</script>

{#if genre}
  <li
    bind:this={ref}
    class={cn(
      genre.parents.length > 0 && 'ml-4 border-l border-gray-200 transition dark:border-gray-800',
    )}
  >
    <div class="flex">
      <IconButton
        size="sm"
        tooltip={isExpanded ? 'Collapse' : 'Expand'}
        class={cn('ml-1 flex-shrink-0 text-gray-500', genre.children.length === 0 && 'invisible')}
        on:click={() => treeState.setExpanded(path, !isExpanded)}
      >
        <ChevronRightIcon class={cn('transition', isExpanded && 'rotate-90')} />
      </IconButton>

      <a
        href="/genres/{id}"
        class={cn(
          'group block flex-1 truncate rounded border border-white border-opacity-0 px-1.5 text-[0.93rem] hover:border-opacity-[0.03] hover:bg-gray-800',
          isSelected ? 'text-primary-500' : 'text-gray-400 hover:text-white',
        )}
        on:click={() => {
          treeState.setSelectedId(id)
          treeState.setSelectedPath(path)
        }}
      >
        {genre.name}
        {#if genre.subtitle}
          {' '}
          <span
            class={cn(
              'text-[0.8rem]',
              isSelected
                ? 'text-primary-500 dark:text-primary-700'
                : 'text-gray-500 group-hover:text-gray-400',
            )}
          >
            [{genre.subtitle}]
          </span>
        {/if}
        {#if $userSettings.showTypeTags && genre.type !== 'STYLE'}
          {' '}
          <GenreTypeChip type={genre.type} />
        {/if}
        {#if $userSettings.showRelevanceTags}
          {' '}
          <RelevanceChip relevance={genre.relevance} />
        {/if}
      </a>
    </div>

    {#if isExpanded && genre.children.length > 0}
      <ul transition:slide|local={{ axis: 'y' }}>
        {#each genre.children as childId (childId)}
          {@const childPath = [...path, childId]}
          <svelte:self id={childId} path={childPath} {treeRef} />
        {/each}
      </ul>
    {/if}
  </li>
{/if}
