// apps/frontend/src/lib/features/genres/components/GenreMultiselect.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query'

  import Loader from '$lib/atoms/Loader.svelte'
  import { Multiselect } from '$lib/atoms/Multiselect'
  import GenreTypeChip from '$lib/components/GenreTypeChip.svelte'
  import { getUserSettingsContext } from '$lib/contexts/user-settings'
  import { createGetGenreQuery } from '$lib/features/genres/queries/application/get-genre'
  import { createSearchGenresQuery } from '$lib/features/genres/queries/application/search'
  import { type GenreStore } from '$lib/features/genres/queries/infrastructure'
  import { type TreeGenre } from '$lib/features/genres/queries/types'
  import { genreQueries } from '$lib/features/genres/tanstack'
  import { useDebounce } from '$lib/runes/use-debounce.svelte'
  import { cn } from '$lib/utils/dom'

  let {
    value = $bindable([]),
    onChange,
    exclude = [],
    id,
    class: class_,
  }: {
    value?: number[]
    onChange?: (value: number[]) => void
    exclude?: number[]
    id?: string
    class?: string
  } = $props()

  const userSettings = getUserSettingsContext()

  let excludeSet = $derived(new Set(exclude))

  let filter = $state('')
  const debouncedFilter = useDebounce(() => filter, 250)

  const genreTreeQuery = createQuery(genreQueries.tree())

  const genres: GenreStore = $derived($genreTreeQuery.data ?? new Map<number, TreeGenre>())

  let options = $derived(
    createSearchGenresQuery(genres)(debouncedFilter.current)
      .filter((match) => !excludeSet.has(match.id) && !value.includes(match.id))
      .slice(0, 100),
  )

  const selectedItems = $derived(
    value.map((id) => ({ id, genre: createGetGenreQuery(genres)(id) })),
  )
</script>

<Multiselect.Root
  value={value.map((v) => v.toString())}
  options={options.map(({ id }) => id.toString())}
  onChange={(vs) => {
    value = vs.map((v) => Number.parseInt(v))
    onChange?.(value)
  }}
  class={class_}
>
  <Multiselect.Trigger>
    {#each selectedItems as { id, genre } (id)}
      <Multiselect.SelectedItem value={id.toString()}>
        {#if genre === undefined}
          {#if !!$genreTreeQuery.data || !!$genreTreeQuery.error}
            Unknown
          {:else}
            <Loader size={10} />
          {/if}
        {:else}
          <div class={cn(genre.nsfw && !$userSettings.showNsfw && 'blur-sm')}>
            <span>{genre.name}</span>{#if genre.subtitle}&nbsp;<span class="text-xs text-gray-500"
                >[{genre.subtitle}]</span
              >{/if}{#if $userSettings.showTypeTags && genre.type !== 'STYLE'}
              &nbsp;
              <GenreTypeChip type={genre.type} class="dark:border dark:border-gray-700" />
            {/if}
          </div>
        {/if}
      </Multiselect.SelectedItem>
    {/each}
    <Multiselect.Input {id} bind:value={filter} />
  </Multiselect.Trigger>
  <Multiselect.Options>
    {#if $genreTreeQuery.data}
      {#each options as genreMatch (genreMatch.id)}
        <Multiselect.Option value={genreMatch.id.toString()}>
          <div class={cn(genreMatch.genre.nsfw && !$userSettings.showNsfw && 'blur-sm')}>
            {genreMatch.genre.name}
            {#if genreMatch.genre.subtitle}
              &nbsp;
              <span class="text-[0.8rem] text-gray-500 group-hover:text-gray-400"
                >[{genreMatch.genre.subtitle}]</span
              >
            {/if}
            {#if genreMatch.matchedAka}
              &nbsp;
              <span class="text-[0.8rem]">({genreMatch.matchedAka})</span>
            {/if}
            {#if $userSettings.showTypeTags && genreMatch.genre.type !== 'STYLE'}
              &nbsp;
              <GenreTypeChip type={genreMatch.genre.type} />
            {/if}
          </div>
        </Multiselect.Option>
      {/each}
    {:else if $genreTreeQuery.error}
      <div class="flex w-full items-center justify-center p-2 text-sm text-error-500">
        Error loading genres
      </div>
    {:else}
      <Loader size={32} />
    {/if}
  </Multiselect.Options>
</Multiselect.Root>

// src/components/GenresPage/GenreView/Form/GenreMultiselect.tsx
import { forwardRef, useMemo, useState } from 'react'

import useDebounce from '../../../../hooks/useDebounce'
import useIdMap from '../../../../hooks/useIdMap'
import {
  useSimpleGenreSearchQuery,
  useSimpleGenresQuery,
} from '../../../../services/genres'
import Button from '../../../common/Button'
import M from '../../../common/Multiselect'
import useGenreNavigatorSettings from '../../GenreNavigator/useGenreNavigatorSettings'
import GenreTypeChip from '../../GenreTypeChip'

const PER_PAGE = 100

export type GenreMultiselectProps = {
  id?: string
  selectedIds: number[]
  excludeIds?: number[]
  onChange: (value: number[]) => void
}

const GenreMultiselect = forwardRef<HTMLInputElement, GenreMultiselectProps>(
  ({ id, selectedIds, excludeIds, onChange }, ref) => {
    const [query, setQuery] = useState('')
    const [debouncedQuery] = useDebounce(query, 200)

    const allGenres = useSimpleGenresQuery()
    const genreMap = useIdMap(allGenres.data ?? [])

    const genreSearchQuery = useSimpleGenreSearchQuery(debouncedQuery)
    const options = useMemo(
      () =>
        genreSearchQuery.data?.filter(({ genre }) => {
          if (excludeIds && excludeIds.includes(genre.id)) return false
          if (selectedIds.includes(genre.id)) return false
          return true
        }),
      [excludeIds, genreSearchQuery.data, selectedIds]
    )

    const [page, setPage] = useState(1)

    const { showTypeTags } = useGenreNavigatorSettings()

    return (
      <M
        query={query}
        onQueryChange={setQuery}
        options={options}
        value={selectedIds.map((id) => ({ id }))}
        onChange={(s) => onChange(s.map(({ id }) => id))}
        ref={ref}
      >
        <M.Box>
          {selectedIds.map((id) => {
            const genre = genreMap.get(id)
            return (
              <M.Selected key={id} item={genre ?? { id }}>
                {genre?.name ?? 'Loading...'}
                {genre?.subtitle && (
                  <>
                    {' '}
                    <span className='text-xs text-gray-500'>
                      [{genre.subtitle}]
                    </span>
                  </>
                )}
                {showTypeTags && genre && genre.type !== 'STYLE' && (
                  <>
                    {' '}
                    <GenreTypeChip
                      type={genre.type}
                      className='bg-gray-300 text-2xs group-hover:bg-error-400 group-hover:text-error-700'
                    />
                  </>
                )}
              </M.Selected>
            )
          })}
          <M.Input id={id} />
        </M.Box>
        <M.Options>
          {options?.slice(0, page * PER_PAGE).map((match) => (
            <M.Option key={match.id} item={match}>
              {match.genre.name}
              {match.genre.subtitle && (
                <>
                  {' '}
                  <span className='text-xs text-gray-600'>
                    [{match.genre.subtitle}]
                  </span>
                </>
              )}
              {match.matchedAka && (
                <>
                  {' '}
                  <span className='text-xs'>({match.matchedAka})</span>
                </>
              )}
              {showTypeTags && match.genre.type !== 'STYLE' && (
                <>
                  {' '}
                  <GenreTypeChip className='text-xs' type={match?.genre.type} />
                </>
              )}
            </M.Option>
          ))}
          {options && options.length > page * PER_PAGE && (
            <div className='flex w-full justify-center'>
              <Button
                type='button'
                template='secondary'
                onClick={() => setPage((p) => p + 1)}
              >
                Load More
              </Button>
            </div>
          )}
        </M.Options>
      </M>
    )
  }
)

GenreMultiselect.displayName = 'GenreMultiselect'

export default GenreMultiselect
