// src/lib/atoms/SplitPane.svelte
<script lang="ts" context="module">
  type PartialTouchEvent = { touches: { [index: number]: { clientX: number } } }
</script>

<script lang="ts">
  import { tw, unfocus } from '$lib/utils/dom'

  let class_: string | undefined = undefined
  export { class_ as class }

  export let defaultSize: number | undefined = undefined
  export let minSize = 50
  export let maxSize: number | undefined = undefined

  export let leftSize = getDefaultSize(defaultSize, minSize, maxSize)

  let active = false
  let pos = 0

  let containerRef: HTMLElement | undefined
  let leftRef: HTMLElement | undefined
  let rightRef: HTMLElement | undefined

  function handleTouchStart(e: PartialTouchEvent) {
    unfocus()
    active = true
    pos = e.touches[0].clientX
  }

  function handleTouchEnd() {
    if (active) {
      active = false
    }
  }

  function handleTouchMove(e: PartialTouchEvent) {
    if (!active || !leftRef || !containerRef) return

    unfocus()

    const { width } = leftRef.getBoundingClientRect()
    const current = e.touches[0].clientX
    const posDelta = pos - current

    let newMaxSize = maxSize
    if (maxSize !== undefined && maxSize <= 0) {
      newMaxSize = containerRef.getBoundingClientRect().width + maxSize
    }

    let newSize = width - posDelta
    const newPos = pos - posDelta

    if (newSize < minSize) {
      newSize = minSize
    } else if (newMaxSize !== undefined && newSize > newMaxSize) {
      newSize = newMaxSize
    } else {
      pos = newPos
    }

    leftSize = newSize
  }

  function handleMouseDown(e: MouseEvent) {
    handleTouchStart({ ...e, touches: [{ clientX: e.clientX }] })
  }

  function handleMouseMove(e: MouseEvent) {
    handleTouchMove({ ...e, touches: [{ clientX: e.clientX }] })
  }

  function getDefaultSize(
    defaultSize: number | undefined,
    minSize: number,
    maxSize: number | undefined,
    draggedSize?: number,
  ) {
    if (draggedSize !== undefined) {
      const min = minSize ?? 0
      const max = maxSize !== undefined && maxSize >= 0 ? maxSize : Number.POSITIVE_INFINITY
      return Math.max(min, Math.min(max, draggedSize))
    }
    if (defaultSize !== undefined) {
      return defaultSize
    }
    return minSize
  }
</script>

<svelte:document
  on:mouseup={handleTouchEnd}
  on:mousemove={handleMouseMove}
  on:touchmove={handleTouchMove}
/>

<div class={tw('flex', class_)} bind:this={containerRef}>
  <div
    class="relative flex-none outline-none"
    style={leftSize === undefined ? undefined : `width: ${leftSize}px;`}
    bind:this={leftRef}
  >
    <slot name="left" />
  </div>
  <button
    class={tw(
      'group w-px cursor-col-resize rounded-full bg-transparent px-1 py-[6px] transition hover:bg-primary-100 dark:hover:bg-primary-950',
      active && 'bg-primary-100 dark:bg-primary-950',
    )}
    on:mousedown={handleMouseDown}
    on:touchstart={handleTouchStart}
    on:touchend={handleTouchEnd}
  >
    <div
      class={tw(
        'h-full w-px bg-transparent transition group-hover:bg-primary-300 dark:group-hover:bg-primary-700',
        active && 'bg-primary-300 dark:bg-gray-800',
      )}
    />
  </button>
  <div class="relative flex-1 outline-none" bind:this={rightRef}>
    <slot name="right" />
  </div>
</div>

// src/components/common/SplitPane/index.tsx
import clsx from 'clsx'
import {
  FC,
  forwardRef,
  ReactElement,
  useCallback,
  useRef,
  useState,
} from 'react'

import useEventListener from '../../../hooks/useEventListener'
import useLocalStorage from '../../../hooks/useLocalStorage'
import { isBrowser, twsx, unfocus } from '../../../utils/dom'

type PartialTouchEvent = { touches: { [index: number]: { clientX: number } } }

const SplitPane: FC<{
  children: [ReactElement, ReactElement]
  defaultSize?: number
  minSize?: number
  maxSize?: number
  className?: string
}> = ({ children, minSize = 50, maxSize, defaultSize, className }) => {
  const [active, setActive] = useState(false)
  const [pos, setPos] = useState(0)
  const [size, setSize] = useLocalStorage(
    'settings.genreTree.size',
    getDefaultSize(defaultSize, minSize, maxSize)
  )

  const splitPaneRef = useRef<HTMLDivElement>(null)
  const pane1Ref = useRef<HTMLDivElement>(null)

  const handleTouchStart = useCallback((e: PartialTouchEvent) => {
    unfocus()
    setActive(true)
    setPos(e.touches[0].clientX)
  }, [])

  const handleTouchEnd = useCallback(() => {
    if (active) {
      setActive(false)
    }
  }, [active])

  const handleTouchMove = useCallback(
    (e: PartialTouchEvent) => {
      if (!active) return

      unfocus()

      const node = pane1Ref.current

      if (!node) return

      const { width } = node.getBoundingClientRect()
      const current = e.touches[0].clientX
      const posDelta = pos - current

      let newMaxSize = maxSize
      if (maxSize !== undefined && maxSize <= 0 && splitPaneRef.current) {
        newMaxSize =
          splitPaneRef.current.getBoundingClientRect().width + maxSize
      }

      let newSize = width - posDelta
      const newPos = pos - posDelta

      if (newSize < minSize) {
        newSize = minSize
      } else if (newMaxSize !== undefined && newSize > newMaxSize) {
        newSize = newMaxSize
      } else {
        setPos(newPos)
      }

      setSize(newSize)
    },
    [active, maxSize, minSize, pos, setSize]
  )

  const handleMouseDown = useCallback(
    (e: React.MouseEvent) =>
      handleTouchStart({
        ...e,
        touches: [{ clientX: e.clientX }],
      }),
    [handleTouchStart]
  )

  const handleMouseMove = useCallback(
    (e: MouseEvent) =>
      handleTouchMove({ ...e, touches: [{ clientX: e.clientX }] }),
    [handleTouchMove]
  )

  const documentRef = useRef(isBrowser ? document : null)
  useEventListener('mouseup', handleTouchEnd, documentRef)
  useEventListener('mousemove', handleMouseMove, documentRef)
  useEventListener('touchmove', handleTouchMove, documentRef)

  return (
    <div ref={splitPaneRef} className={twsx('flex', className)}>
      <Pane ref={pane1Ref} size={size}>
        {children[0]}
      </Pane>
      <div
        className={twsx(
          'group w-px cursor-col-resize bg-transparent px-1 transition hover:bg-gray-100',
          active && 'bg-gray-100'
        )}
        onMouseDown={handleMouseDown}
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
      >
        <div
          className={twsx(
            'h-full w-px bg-gray-200 transition group-hover:bg-gray-300',
            active && 'bg-gray-300'
          )}
        />
      </div>
      <Pane>{children[1]}</Pane>
    </div>
  )
}

const Pane = forwardRef<
  HTMLDivElement,
  { children: ReactElement; size?: number }
>(({ children, size }, ref) => (
  <div
    ref={ref}
    className={clsx(
      'relative outline-none',
      size === undefined ? 'flex-1' : 'flex-none'
    )}
    style={{ width: size }}
  >
    {children}
  </div>
))

Pane.displayName = 'Pane'

const getDefaultSize = (
  defaultSize: number | undefined,
  minSize: number,
  maxSize: number | undefined,
  draggedSize?: number
) => {
  if (draggedSize !== undefined) {
    const min = minSize ?? 0
    const max =
      maxSize !== undefined && maxSize >= 0 ? maxSize : Number.POSITIVE_INFINITY
    return Math.max(min, Math.min(max, draggedSize))
  }
  if (defaultSize !== undefined) {
    return defaultSize
  }
  return minSize
}

export default SplitPane
