// src/components/GenresPage/RelevanceSelect.tsx
import { forwardRef, useMemo } from 'react'
import { range } from 'remeda'

import {
  MAX_GENRE_RELEVANCE,
  MIN_GENRE_RELEVANCE,
  UNSET_GENRE_RELEVANCE,
} from '../../server/db/common/inputs'
import Select from '../common/Select'
import { getGenreRelevanceText } from './utils'

const RelevanceSelect = forwardRef<
  HTMLButtonElement,
  {
    id?: string
    value?: number
    onChange: (value: number) => void
  }
>(({ id, value, onChange }, ref) => {
  const relevanceOptions = useMemo(
    () => [
      ...range(MIN_GENRE_RELEVANCE, MAX_GENRE_RELEVANCE + 1)
        .reverse()
        .map((r) => ({
          key: r,
          label: `${r} - ${getGenreRelevanceText(r)}`,
        })),
      { key: UNSET_GENRE_RELEVANCE, label: 'Unset' },
    ],
    []
  )

  const selectedOption = useMemo(
    () => relevanceOptions.find((ro) => ro.key === value),
    [relevanceOptions, value]
  )

  return (
    <Select
      id={id}
      ref={ref}
      options={relevanceOptions}
      value={selectedOption}
      onChange={(v) => onChange(v.key)}
    />
  )
})

RelevanceSelect.displayName = 'RelevanceSelect'

export default RelevanceSelect

// apps/frontend/src/lib/features/genres/components/RelevanceSelect.svelte
<script lang="ts">
  import { Select } from '$lib/atoms/Select'
  import {
    getGenreRelevanceText,
    MAX_GENRE_RELEVANCE,
    MIN_GENRE_RELEVANCE,
    UNSET_GENRE_RELEVANCE,
  } from '$lib/types/genres'
  import { range } from '$lib/utils/array'
  import { ifDefined } from '$lib/utils/types'

  type Props = {
    id?: string
    class?: string
    value?: number
    onChange?: (value: number | undefined) => void
  }

  let { value = $bindable(undefined), id, class: class_, onChange }: Props = $props()

  const options = [
    ...range(MIN_GENRE_RELEVANCE, MAX_GENRE_RELEVANCE + 1).reverse(),
    UNSET_GENRE_RELEVANCE,
  ]

  function displayRelevance(relevance: number | undefined) {
    if (relevance === undefined || relevance === UNSET_GENRE_RELEVANCE) {
      return getGenreRelevanceText(relevance)
    } else {
      return `${relevance} - ${getGenreRelevanceText(relevance)}`
    }
  }
</script>

<Select.Root
  value={value?.toString()}
  options={options.map((v) => v.toString())}
  onChange={(vs) => {
    const v = ifDefined(vs, Number.parseInt)
    value = v
    onChange?.(v)
  }}
  class={class_}
>
  <Select.Trigger {id}>
    {displayRelevance(value)}
  </Select.Trigger>
  <Select.Options>
    {#each options as option (option)}
      <Select.Option value={option.toString()}>
        {displayRelevance(option)}
      </Select.Option>
    {/each}
  </Select.Options>
</Select.Root>
