// apps/frontend/src/lib/components/GenreTypeChip.svelte
<script lang="ts">
  import Chip from '$lib/atoms/Chip.svelte'
  import type { GenreType } from '$lib/types/genres'
  import { cn } from '$lib/utils/dom'

  type Props = {
    type: GenreType
    class?: string
  }

  let { type, class: class_ }: Props = $props()

  const GenreTypeChipNames: Record<GenreType, string> = {
    MOVEMENT: 'Mvmt',
    META: 'Meta',
    STYLE: 'Style',
    TREND: 'Trend',
    SCENE: 'Scene',
  }
</script>

<Chip text={GenreTypeChipNames[type]} class={cn('genre-type-chip', class_)} />

// src/components/GenresPage/GenreTypeChip.tsx
import { GenreType } from '../../server/db/genre/outputs'
import { GenreTypeNames, GenreTypeChipNames } from '../../utils/genres'
import Chip from '../common/Chip'
import { FC, useMemo } from 'react'

const GenreTypeChip: FC<{ type: GenreType; className?: string }> = ({
  type,
  className,
}) => {
  const title = useMemo(() => GenreTypeNames[type], [type])
  const text = useMemo(() => GenreTypeChipNames[type], [type])

  return <Chip text={text} title={title} className={className} />
}

export default GenreTypeChip
