// src/lib/atoms/Button.svelte
<script lang="ts" context="module">
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  type C = typeof SvelteComponentTyped<any, any, any>
</script>

<script lang="ts" generics="C extends typeof SvelteComponentTyped<any, any, any>">
  import type { SvelteComponentTyped } from 'svelte'
  import { scale } from 'svelte/transition'

  import { tooltip } from '$lib/actions/tooltip'
  import { slide } from '$lib/transitions/slide'
  import { cn, tw } from '$lib/utils/dom'

  import Loader from './Loader.svelte'

  export let disabled = false
  export let type: 'button' | 'submit' = 'button'
  export let kind: 'solid' | 'outline' | 'text' = 'solid'
  export let align: 'left' | 'center' | 'right' = 'center'
  export let loading = false
  let class_: string | undefined = undefined
  export { class_ as class }
  let tooltip_: string | undefined = undefined
  export { tooltip_ as tooltip }
  export let color: 'primary' | 'secondary' | 'error' = 'primary'

  export let icon: C | undefined = undefined
  export let iconClass: string | undefined = undefined

  export let layer: 700 | 800 = 800
</script>

<button
  on:click
  {disabled}
  {type}
  class={tw(
    'relative flex items-center rounded border px-4 py-1 text-sm font-medium transition',

    align === 'left' && 'justify-start',
    align === 'center' && 'justify-center',
    align === 'right' && 'justify-end',

    kind === 'solid' &&
      cn(
        'border-transparent text-black disabled:bg-gray-500 disabled:text-gray-700',
        color === 'primary' && 'bg-primary-500 hover:bg-primary-600',
        color === 'secondary' && 'bg-secondary-500 hover:bg-secondary-600',
        color === 'error' && 'bg-error-600 text-error-100 hover:bg-error-700',
      ),

    kind === 'outline' &&
      cn(
        'bg-transparent disabled:border-gray-500 disabled:bg-transparent disabled:text-gray-500',
        layer === 700 && 'hover:bg-gray-600',
        layer === 800 && 'hover:bg-gray-700',
        color === 'primary' && 'border-primary-500 text-primary-500',
        color === 'secondary' && 'border-secondary-500 text-secondary-500',
        color === 'error' && 'border-error-500 text-error-500',
      ),

    kind === 'text' &&
      cn(
        'border-transparent bg-transparent disabled:bg-transparent disabled:text-gray-500',
        layer === 700 && 'hover:bg-gray-600',
        layer === 800 && 'hover:bg-gray-700',
        color === 'primary' && 'text-primary-500',
        color === 'secondary' && 'text-secondary-500',
        color === 'error' && 'text-error-500',
      ),

    class_,
  )}
>
  {#if loading || icon}
    <div transition:slide|local={{ axis: 'x' }}>
      <div class="relative mr-2 h-3.5 w-3.5">
        {#if loading}
          <Loader />
        {:else}
          <div class="absolute" transition:scale|local={{ duration: 150 }}>
            <svelte:component this={icon} class={iconClass} />
          </div>
        {/if}
      </div>
    </div>
  {/if}

  <slot />

  {#if tooltip_ !== undefined}
    <div class="absolute left-0 top-0 h-full w-full" use:tooltip={{ content: tooltip_ }} />
  {/if}
</button>

// src/components/common/Button.tsx
import { ButtonHTMLAttributes, FC, PropsWithChildren } from 'react'

import { twsx } from '../../utils/dom'
import Loader from './Loader'

export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  template?: 'primary' | 'secondary' | 'tertiary' | 'danger'
  loading?: boolean
}

const Button: FC<PropsWithChildren<ButtonProps>> = ({
  template = 'primary',
  children,
  className,
  loading,
  disabled,
  ...props
}) => {
  return (
    <button
      className={twsx(
        'flex items-center justify-center font-semibold text-sm py-1 px-3 rounded outline-none transition',
        (disabled || loading) && 'pointer-events-none',
        template === 'primary' &&
          (disabled
            ? 'bg-gray-300 text-gray-500 border border-transparent'
            : 'bg-primary-500 hover:bg-primary-600 active:bg-primary-700 text-gray-100 border border-transparent focus:border-secondary-500'),
        template === 'secondary' &&
          (disabled
            ? 'bg-transparent text-gray-400 border border-gray-400'
            : 'bg-transparent text-primary-500 hover:text-primary-600 active:text-primary-700 border border-primary-500 hover:border-primary-600 active:border-primary-700 focus:border-secondary-500'),
        template === 'tertiary' &&
          (disabled
            ? 'bg-transparent text-gray-400 border border-transparent'
            : 'bg-transparent hover:bg-gray-200 active:bg-gray-300 text-primary-500 border border-transparent focus:border-secondary-500'),
        template === 'danger' &&
          (disabled
            ? 'bg-gray-300 text-gray-500 border border-transparent'
            : 'bg-error-500 hover:bg-error-600 active:bg-error-700 text-gray-100 border border-transparent focus:border-error-800'),
        className
      )}
      disabled={disabled || loading}
      {...props}
    >
      {loading && <Loader className='text-inherit mr-1.5' size={14} />}
      {children}
    </button>
  )
}

export default Button
