// apps/frontend/src/lib/atoms/Label.svelte
<script lang="ts">
  import { type Snippet } from 'svelte'

  import { tw } from '$lib/utils/dom'

  type Props = {
    for?: string
    class?: string
    children?: Snippet
  }

  let { for: for_, class: class_, children }: Props = $props()
</script>

<label class={tw('text-sm text-gray-600 transition dark:text-gray-400', class_)} for={for_}>
  {@render children?.()}
</label>

// src/components/common/Label.tsx
import { FC, LabelHTMLAttributes } from 'react'

import { twsx } from '../../utils/dom'

export type LabelProps = LabelHTMLAttributes<HTMLLabelElement> & {
  error?: unknown
}

const Label: FC<LabelProps> = ({ children, error, className, ...props }) => (
  <label
    className={twsx(
      'block text-sm',
      error ? 'text-error-600' : 'text-gray-700',
      className
    )}
    {...props}
  >
    {children}
  </label>
)

export default Label
