// apps/frontend/src/lib/components/Romcode/RomcodeEditor/RomcodeEditor.svelte
<script lang="ts" module>
  const Tabs = Object.freeze({
    EDIT: 'Edit',
    VIEW: 'View',
  })
  type Tab = (typeof Tabs)[keyof typeof Tabs]
</script>

<script lang="ts">
  import { Link, TextB, TextItalic } from 'phosphor-svelte'

  import IconButton from '$lib/atoms/IconButton.svelte'
  import { makeGenreTag } from '$lib/types/genres'
  import { cn, tw } from '$lib/utils/dom'

  import Romcode from '../Romcode.svelte'
  import GenreSearchDialog from './GenreSearchDialog.svelte'

  type Props = {
    id?: string
    value?: string
    disabled?: boolean
    autofocus?: boolean
    class?: string
    onChange?: (value: string) => void
  }

  let {
    id,
    value = $bindable(''),
    disabled = false,
    autofocus = false,
    class: class_,
    onChange,
  }: Props = $props()

  let tab: Tab = $state(Tabs.EDIT)
  let showGenreDialog: boolean | string = $state(false)

  let ta: HTMLTextAreaElement | undefined = $state()

  $effect(() => {
    onChange?.(value)
  })

  function handleInsertGenreTag(id: number) {
    const genreTag = makeGenreTag(id)
    if (ta && (ta.selectionStart || ta.selectionStart === 0)) {
      const startPos = ta.selectionStart
      const endPos = ta.selectionEnd

      const updatedValue = value.slice(0, startPos) + genreTag + value.slice(endPos)

      ta.value = updatedValue
      ta.focus()
      ta.selectionStart = startPos + genreTag.length
      ta.selectionEnd = startPos + genreTag.length

      value = updatedValue
    } else {
      value = value + genreTag
    }
  }

  function handleBold() {
    if (!ta) return

    const startPos = ta.selectionStart
    const endPos = ta.selectionEnd

    const updatedValue =
      value.slice(0, startPos) + '**' + value.slice(startPos, endPos) + '**' + value.slice(endPos)

    ta.value = updatedValue
    ta.focus()
    ta.selectionStart = endPos + 4
    ta.selectionEnd = endPos + 4

    value = updatedValue
  }

  function handleItalic() {
    if (!ta) return

    const startPos = ta.selectionStart
    const endPos = ta.selectionEnd

    const updatedValue =
      value.slice(0, startPos) + '*' + value.slice(startPos, endPos) + '*' + value.slice(endPos)

    ta.value = updatedValue
    ta.focus()
    ta.selectionStart = endPos + 2
    ta.selectionEnd = endPos + 2

    value = updatedValue
  }
</script>

<div
  class={tw(
    'flex h-72 resize-y flex-col overflow-auto rounded border border-gray-300 text-sm text-gray-800 transition focus-within:border-secondary-500 dark:border-gray-600 dark:text-gray-200',
    class_,
  )}
>
  {#if tab === Tabs.EDIT}
    <div class="flex flex-1 flex-col">
      <div
        class="flex border-b border-gray-300 bg-gray-100 transition dark:border-gray-700 dark:bg-gray-900"
      >
        <IconButton class="rounded-none" tooltip="Bold" onClick={() => handleBold()}>
          <TextB />
        </IconButton>
        <IconButton class="rounded-none" tooltip="Italic" onClick={() => handleItalic()}>
          <TextItalic />
        </IconButton>
        <IconButton
          class="rounded-none"
          tooltip="Insert genre link"
          onClick={() => {
            if (!ta) {
              showGenreDialog = true
              return
            }

            const startPos = ta.selectionStart
            const endPos = ta.selectionEnd
            const selectedText = value.slice(startPos, endPos)
            showGenreDialog = selectedText || true
          }}
        >
          <Link />
        </IconButton>
      </div>

      <!-- svelte-ignore a11y_autofocus -->
      <textarea
        bind:this={ta}
        {id}
        class="flex-1 resize-none bg-black bg-opacity-[0.04] p-1.5 transition hover:bg-opacity-[0.07] focus:outline-none dark:bg-white dark:bg-opacity-5 dark:hover:bg-opacity-10"
        bind:value
        {disabled}
        {autofocus}
      >
      </textarea>
    </div>
  {:else if tab === Tabs.VIEW}
    <div class="flex-1 overflow-auto px-2 py-1">
      <Romcode data={value} />
    </div>
  {/if}

  <div
    class="flex border-t border-gray-300 bg-gray-100 transition dark:border-gray-700 dark:bg-gray-900"
  >
    <button
      class={cn(
        'border-r border-gray-200 px-2 py-1 text-xs uppercase text-gray-400 transition hover:bg-gray-200 active:bg-gray-300 dark:border-gray-700 dark:hover:bg-gray-800 dark:active:bg-gray-700',
        tab === Tabs.EDIT ? 'font-bold' : 'font-medium',
      )}
      type="button"
      onclick={() => (tab = Tabs.EDIT)}
    >
      Edit
    </button>
    <button
      class={cn(
        'border-r border-gray-200 px-2 py-1 text-xs uppercase text-gray-400 transition hover:bg-gray-200 active:bg-gray-300 dark:border-gray-700 dark:hover:bg-gray-800 dark:active:bg-gray-700',
        tab === Tabs.VIEW ? 'font-bold' : 'font-medium',
      )}
      type="button"
      onclick={() => (tab = Tabs.VIEW)}
    >
      View
    </button>
  </div>
</div>

{#if showGenreDialog}
  <GenreSearchDialog
    filter={typeof showGenreDialog === 'string' ? showGenreDialog : undefined}
    on:close={() => (showGenreDialog = false)}
    on:select={(e) => {
      handleInsertGenreTag(e.detail.id)
      showGenreDialog = false
    }}
  />
{/if}

// src/components/common/RomcodeEditor.tsx
import clsx from 'clsx'
import {
  ChangeEventHandler,
  FocusEventHandler,
  forwardRef,
  useState,
} from 'react'

import { twsx } from '../../utils/dom'
import Romcode from './Romcode'

enum Tab {
  EDIT,
  VIEW,
}

const RomcodeEditor = forwardRef<
  HTMLTextAreaElement,
  {
    id?: string
    value: string
    onChange: ChangeEventHandler<HTMLTextAreaElement>
    onBlur: FocusEventHandler<HTMLTextAreaElement>
    className?: string
  }
>(({ id, value, onChange, onBlur, className }, ref) => {
  const [tab, setTab] = useState<Tab>(Tab.EDIT)

  return (
    <div
      className={twsx(
        'group flex flex-col h-72 overflow-auto resize-y rounded border border-gray-500 bg-gray-100 hover:bg-gray-200 active:bg-gray-300 focus-within:border-secondary-500 transition text-sm text-gray-800',
        className
      )}
    >
      {tab === Tab.EDIT && (
        <textarea
          ref={ref}
          id={id}
          className='flex-1 resize-none bg-transparent p-1.5 focus:outline-none'
          value={value}
          onChange={onChange}
          onBlur={onBlur}
          style={{ flex: 1, resize: 'none' }}
        />
      )}
      {tab === Tab.VIEW && (
        <div className='flex-1 overflow-auto px-2 py-1'>
          <Romcode>{value}</Romcode>
        </div>
      )}
      <div className='flex border-t border-gray-200 transition group-hover:border-gray-300 group-active:border-gray-400'>
        <button
          className={clsx(
            'border-r border-gray-200 px-2 py-1 text-xs uppercase text-gray-400 transition hover:bg-gray-100 group-hover:border-gray-300 group-hover:text-gray-500 group-active:border-gray-400 group-active:text-gray-600',
            tab === Tab.EDIT ? 'font-bold' : 'font-medium'
          )}
          type='button'
          onClick={() => setTab(Tab.EDIT)}
        >
          Edit
        </button>
        <button
          className={clsx(
            'border-r border-gray-200 px-2 py-1 text-xs uppercase text-gray-400 transition hover:bg-gray-100 group-hover:border-gray-300 group-hover:text-gray-500 group-active:border-gray-400 group-active:text-gray-600',
            tab === Tab.VIEW ? 'font-bold' : 'font-medium'
          )}
          type='button'
          onClick={() => setTab(Tab.VIEW)}
        >
          View
        </button>
      </div>
    </div>
  )
})

RomcodeEditor.displayName = 'RomcodeEditor'

export default RomcodeEditor
