// src/components/GenresPage/GenreNavigator/index.tsx
import { Permission } from '@prisma/client'
import Link from 'next/link'
import { FC, useCallback, useState } from 'react'
import { RiSettings3Fill } from 'react-icons/ri'

import useDebouncedState from '../../../hooks/useDebouncedState'
import { useSession } from '../../../services/auth'
import { twsx } from '../../../utils/dom'
import Button from '../../common/Button'
import IconButton from '../../common/IconButton'
import Input from '../../common/Input'
import GenreSearchResults from './Search'
import GenreNavigatorSettings from './Settings'
import GenreTree from './Tree'

const GenreNavigator: FC<{ className?: string }> = ({ className }) => {
  const session = useSession()

  const [showSettings, setShowSettings] = useState(false)
  const [filter, setFilter] = useState('')
  const [debouncedFilter, setDebouncedFilter] = useDebouncedState(filter, 500)

  const clearFilter = useCallback(() => {
    setFilter('')
    setDebouncedFilter('')
  }, [setDebouncedFilter])

  return (
    <div className={twsx('flex h-full w-full flex-col', className)}>
      <div className='flex space-x-1 border-b border-gray-100 p-4'>
        <div className='relative flex-1'>
          <Input
            value={filter}
            onChange={setFilter}
            placeholder='Filter...'
            showClear
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                setFilter(e.currentTarget.value)
                setDebouncedFilter(e.currentTarget.value)
              }
            }}
          />
        </div>
        <div className='flex h-full items-center'>
          <IconButton
            title='Settings'
            onClick={() => setShowSettings(!showSettings)}
          >
            <RiSettings3Fill />
          </IconButton>
        </div>
      </div>
      {showSettings && (
        <div className='border-b p-4'>
          <GenreNavigatorSettings />
        </div>
      )}
      {debouncedFilter && (
        <div className='flex justify-center border-b border-gray-100'>
          <Button
            template='tertiary'
            className='w-full'
            onClick={() => clearFilter()}
          >
            Back to Tree
          </Button>
        </div>
      )}
      <div className='flex-1 overflow-auto'>
        {debouncedFilter ? (
          <GenreSearchResults
            filter={debouncedFilter}
            clearFilter={clearFilter}
          />
        ) : (
          <GenreTree />
        )}
      </div>
      {session.isLoggedIn && session.hasPermission(Permission.EDIT_GENRES) && (
        <div className='border-t p-1'>
          <Link href={{ pathname: '/genres', query: { view: 'create' } }}>
            <a className='w-full'>
              <Button template='secondary' className='w-full'>
                New Genre
              </Button>
            </a>
          </Link>
        </div>
      )}
    </div>
  )
}

export default GenreNavigator

// src/routes/genres/GenreNavigator/GenreNavigator.svelte
<script lang="ts">
  import Button from '$lib/atoms/Button.svelte'
  import Card from '$lib/atoms/Card.svelte'
  import IconButton from '$lib/atoms/IconButton.svelte'
  import Input from '$lib/atoms/Input.svelte'
  import Loader from '$lib/atoms/Loader.svelte'
  import { user } from '$lib/contexts/user'
  import SettingsIcon from '$lib/icons/SettingsIcon.svelte'
  import { slide } from '$lib/transitions/slide'

  import GenreNavigatorSettings from './GenreNavigatorSettings.svelte'
  import GenreSearchResults from './GenreSearchResults.svelte'
  import GenreTree from './GenreTree/GenreTree.svelte'
  import type { TreeGenre } from './GenreTree/state'
  import { searchStore } from './state'

  export let genres: Promise<TreeGenre[]>

  let showSettings = false
  $: isSearching = $searchStore.debouncedFilter
</script>

<Card class="flex h-full w-full flex-col">
  <div class="flex space-x-1 border-b border-gray-200 p-4 transition dark:border-gray-800">
    <div class="relative flex-1">
      <Input
        class="w-full"
        value={$searchStore.filter}
        on:input={(e) => searchStore.setFilter(e.currentTarget.value)}
        placeholder="Filter..."
        on:keydown={(e) => {
          if (e.key === 'Enter') {
            searchStore.setFilterImmediately(e.currentTarget.value)
          }
        }}
      />
    </div>
    <div class="flex h-full items-center">
      <IconButton tooltip="Settings" on:click={() => (showSettings = !showSettings)}>
        <SettingsIcon />
      </IconButton>
    </div>
  </div>

  {#if showSettings}
    <div
      class="space-y-3 border-b border-gray-200 p-4 transition dark:border-gray-800"
      transition:slide|local={{ axis: 'y' }}
    >
      <GenreNavigatorSettings />
    </div>
  {/if}

  {#if isSearching}
    <div class="flex justify-center">
      <Button kind="text" class="w-full" on:click={() => searchStore.clearFilter()}>
        Back to Tree
      </Button>
    </div>
  {/if}

  <div class="flex-1 overflow-auto">
    {#await genres}
      <div class="center h-full max-h-96 w-full">
        <Loader size={32} class="text-primary-500" />
      </div>
    {:then genres}
      {#if isSearching}
        <GenreSearchResults {genres} />
      {:else}
        <GenreTree {genres} />
      {/if}
    {/await}
  </div>

  {#if $user && $user.permissions?.includes('EDIT_GENRES')}
    <div class="border-t border-gray-200 p-1 transition dark:border-gray-800">
      <a href="/genres/create" class="w-full">
        <Button kind="outline" class="w-full">New Genre</Button>
      </a>
    </div>
  {/if}
</Card>
