// src/components/GenrePage/GenreNavigator.tsx
import { Permission } from '@prisma/client'
import Link from 'next/link'
import { FC, useCallback, useState } from 'react'
import { RiCloseFill, RiSettings3Fill } from 'react-icons/ri'

import useDebounce from '../../hooks/useDebounce'
import { useSession } from '../../services/auth'
import { ButtonSecondary, ButtonTertiary } from '../common/Button'
import GenreSearchResults from './GenreSearchResults'
import GenreTree from './GenreTree'
import GenreTreeSettings from './GenreTreeSettings'

const GenreNavigator: FC<{ selectedGenreId?: number }> = ({
  selectedGenreId,
}) => {
  const session = useSession()

  const [showSettings, setShowSettings] = useState(false)
  const [filter, setFilter] = useState('')
  const [debouncedFilter, setDebouncedFilter] = useDebounce(filter, 200)

  const clearFilter = useCallback(() => {
    setFilter('')
    setDebouncedFilter('')
  }, [setDebouncedFilter])

  return (
    <div className='w-full h-full flex flex-col'>
      <div className='p-4 flex space-x-1 border-b'>
        <div className='flex-1 relative'>
          <input
            className='border rounded-sm p-1 px-2 pr-7 w-full'
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            placeholder='Filter...'
          />
          {filter && (
            <div className='absolute right-1 top-0 h-full flex items-center'>
              <button
                className='p-1 hover:bg-gray-200 rounded-full text-gray-500'
                onClick={() => clearFilter()}
              >
                <RiCloseFill />
              </button>
            </div>
          )}
        </div>
        <button
          className='p-2 hover:bg-blue-100 hover:text-blue-600 rounded-sm text-gray-500'
          title='Settings'
          onClick={() => setShowSettings(!showSettings)}
        >
          <RiSettings3Fill />
        </button>
      </div>
      {showSettings && (
        <div className='border-b p-4'>
          <GenreTreeSettings />
        </div>
      )}
      {debouncedFilter && (
        <div className='border-b flex justify-center'>
          <ButtonTertiary className='w-full' onClick={() => clearFilter()}>
            Back to Tree
          </ButtonTertiary>
        </div>
      )}
      <div className='flex-1 overflow-auto'>
        {debouncedFilter ? (
          <GenreSearchResults
            filter={debouncedFilter}
            clearFilter={clearFilter}
          />
        ) : (
          <GenreTree selectedGenreId={selectedGenreId} />
        )}
      </div>
      {session.isLoggedIn && session.hasPermission(Permission.EDIT_GENRES) && (
        <div className='p-1 border-t'>
          <Link href={{ pathname: '/genres/create' }}>
            <a className='w-full'>
              <ButtonSecondary className='w-full'>New Genre</ButtonSecondary>
            </a>
          </Link>
        </div>
      )}
    </div>
  )
}

export default GenreNavigator

// src/routes/genres/GenreNavigator/GenreNavigator.svelte
<script lang="ts">
  import Button from '$lib/atoms/Button.svelte'
  import Card from '$lib/atoms/Card.svelte'
  import IconButton from '$lib/atoms/IconButton.svelte'
  import Input from '$lib/atoms/Input.svelte'
  import Loader from '$lib/atoms/Loader.svelte'
  import { user } from '$lib/contexts/user'
  import SettingsIcon from '$lib/icons/SettingsIcon.svelte'
  import { slide } from '$lib/transitions/slide'

  import GenreNavigatorSettings from './GenreNavigatorSettings.svelte'
  import GenreSearchResults from './GenreSearchResults.svelte'
  import GenreTree from './GenreTree/GenreTree.svelte'
  import type { TreeGenre } from './GenreTree/state'
  import { searchStore } from './state'

  export let genres: Promise<TreeGenre[]>

  let showSettings = false
  $: isSearching = $searchStore.debouncedFilter
</script>

<Card class="flex h-full w-full flex-col">
  <div
    class="flex items-center space-x-1 border-b border-gray-200 p-4 transition dark:border-gray-800"
  >
    <div class="relative flex-1">
      <Input
        ariaLabel="Search Genres"
        class="w-full"
        value={$searchStore.filter}
        on:input={(e) => searchStore.setFilter(e.currentTarget.value)}
        placeholder="Search genres..."
        on:keydown={(e) => {
          if (e.key === 'Enter') {
            searchStore.setFilterImmediately(e.currentTarget.value)
          }
        }}
      />
    </div>
    {#if $user}
      <IconButton tooltip="Genre Settings" on:click={() => (showSettings = !showSettings)}>
        <SettingsIcon />
      </IconButton>
    {/if}
  </div>

  {#if showSettings}
    <div
      class="space-y-3 border-b border-gray-200 p-4 transition dark:border-gray-800"
      transition:slide|local={{ axis: 'y' }}
    >
      <GenreNavigatorSettings />
    </div>
  {/if}

  {#if isSearching}
    <div class="flex justify-center border-b border-gray-200 transition dark:border-gray-800">
      <Button kind="text" class="w-full rounded-none" on:click={() => searchStore.clearFilter()}>
        Back to Tree
      </Button>
    </div>
  {/if}

  <div class="flex-1 overflow-auto">
    {#await genres}
      <div class="center h-full max-h-96 w-full">
        <Loader size={32} class="text-primary-500" />
      </div>
    {:then genres}
      {#if isSearching}
        <GenreSearchResults {genres} />
      {:else}
        <GenreTree {genres} />
      {/if}
    {/await}
  </div>

  {#if $user && $user.permissions?.includes('EDIT_GENRES')}
    <div class="border-t border-gray-200 p-1 transition dark:border-gray-800">
      <a href="/genres/create" class="w-full">
        <Button kind="outline" class="w-full">New Genre</Button>
      </a>
    </div>
  {/if}
</Card>
