// src/components/GenrePage/GenreSearchResults.tsx
import { Permission } from '@prisma/client'
import Link from 'next/link'
import { FC } from 'react'

import { useSession } from '../../services/auth'
import { Match, useSimpleGenreSearchQuery } from '../../services/genres'
import { CenteredLoader } from '../common/Loader'
import { useGenrePageContext } from './context'
import GenreTypeChip from './GenreTypeChip'
import useGenreTreeSettings from './useGenreTreeSettings'

const GenreSearchResults: FC<{ filter: string; clearFilter: () => void }> = ({
  filter,
  clearFilter,
}) => {
  const genresQuery = useSimpleGenreSearchQuery(filter)

  if (genresQuery.data) {
    return <HasData matches={genresQuery.data} clearFilter={clearFilter} />
  }

  if (genresQuery.error) {
    return (
      <div className='w-full h-full flex items-center justify-center text-red-600'>
        Error fetching results :(
      </div>
    )
  }

  return <CenteredLoader />
}

const HasData: FC<{ matches: Match[]; clearFilter: () => void }> = ({
  matches,
  clearFilter,
}) => {
  const session = useSession()

  return (
    <div className='p-4'>
      {matches.length > 0 ? (
        matches.map((match) => (
          <SearchResult
            key={match.genre.id}
            match={match}
            clearFilter={clearFilter}
          />
        ))
      ) : (
        <div className='w-full flex flex-col items-center justify-center text-gray-400'>
          <div>No genres found.</div>
          {session.isLoggedIn && session.hasPermission(Permission.EDIT_GENRES) && (
            <div>
              <Link href={{ pathname: '/genres', query: { view: 'create' } }}>
                <a>
                  <button className='text-blue-500 hover:underline'>
                    Create one.
                  </button>
                </a>
              </Link>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

const SearchResult: FC<{ match: Match; clearFilter: () => void }> = ({
  match: { genre, matchedAka },
  clearFilter,
}) => {
  const { showTypeTags } = useGenreTreeSettings()
  const { setSelectedPath } = useGenrePageContext()

  return (
    <Link href={{ pathname: '/genres', query: { id: genre.id.toString() } }}>
      <a
        className='block text-gray-700 hover:font-bold'
        onClick={() => {
          clearFilter()
          setSelectedPath(undefined)
        }}
      >
        {genre.name}
        {genre?.subtitle && (
          <>
            {' '}
            <span className='text-sm text-gray-600'>[{genre.subtitle}]</span>
          </>
        )}
        {matchedAka && (
          <>
            {' '}
            <span className='text-sm'>({matchedAka})</span>
          </>
        )}
        {showTypeTags && genre.type !== 'STYLE' && (
          <>
            {' '}
            <GenreTypeChip type={genre.type} />
          </>
        )}
      </a>
    </Link>
  )
}

export default GenreSearchResults

// src/routes/genres/GenreNavigator/GenreSearchResults.svelte
<script lang="ts" context="module">
</script>

<script lang="ts">
  import VirtualList from '$lib/atoms/VirtualList.svelte'
  import GenreTypeChip from '$lib/components/GenreTypeChip.svelte'
  import { user, userSettings } from '$lib/contexts/user'
  import { searchGenres } from '$lib/types/genres'

  import type { TreeGenre } from './GenreTree/state'
  import { searchStore } from './state'

  export let genres: TreeGenre[]

  $: matches = searchGenres(genres, $searchStore.debouncedFilter)
</script>

<div class="h-full overflow-auto p-4">
  {#if matches.length > 0}
    <VirtualList items={matches} let:item={match}>
      <a
        href={`/genres/${match.genre.id}`}
        class="block text-gray-700 hover:font-bold dark:text-gray-300"
        on:click={() => searchStore.clearFilter()}
      >
        {match.genre.name}
        {#if match.genre.subtitle}
          {' '}
          <span class="text-sm text-gray-600">[{match.genre.subtitle}]</span>
        {/if}
        {#if match.matchedAka}
          {' '}
          <span class="text-sm">({match.matchedAka})</span>
        {/if}
        {#if $userSettings.showTypeTags && match.genre.type !== 'STYLE'}
          {' '}
          <GenreTypeChip type={match.genre.type} />
        {/if}
      </a>
    </VirtualList>
  {:else}
    <div class="flex w-full flex-col items-center justify-center text-gray-400">
      <div>No genres found.</div>
      {#if $user && $user.permissions?.includes('EDIT_GENRES')}
        <div>
          <a href="/genres?view=create" class="text-primary-500 hover:underline">Create one.</a>
        </div>
      {/if}
    </div>
  {/if}
</div>
